### ISSUE TITLE
New Company Name

### ISSUE THREAD

**Issue by MikeScott97** [KaukinenConfed/Project_2018#3]
The company name is unprofessional so it should be changed. 

I suggest "Ontario Sustainability and Fitness Center" based on the nature of the facilities.

**Comment by Mamodeo** [comment]
That could work, I was thinking more tongue-in-cheek like "Kaukinen Advanced Laboratories"

Also, I believe he said only create one issue thread?

**Comment by KaukinenConfed** [comment]
Duplicate forum
